import type { ControlCenterSectionId } from "@/store/types";

export type PluginPermission = "restricted" | "full-access";

export interface PluginSpec {
  id: string;
  name: string;
  version: string;
  category: string;
  permission: PluginPermission;
  description: string;
  source: string;
  contributions: string[];
  accent: string;
  headline: string;
  actionLabel: string;
  actionTarget: "dashboard" | "tasks" | "meeting" | "settings";
  controlCenterSectionId?: ControlCenterSectionId;
}

export interface PluginPackSpec {
  id: string;
  iconLabel: string;
  title: string;
  description: string;
  pluginIds: string[];
  accent: string;
}

const INTERNAL_PLUGIN_CATALOG: PluginSpec[] = [
  {
    id: "desk-tools",
    name: "Desk Tools",
    version: "1.0.0",
    category: "Internal",
    permission: "restricted",
    description: "Core Desk actions and internal workspace helpers bundled with the product.",
    source: "Built-in",
    contributions: ["desk actions", "context presets", "async workflows"],
    accent: "#7dd3fc",
    headline: "Turn Desk context into reusable next-step prompts and bundles.",
    actionLabel: "Open Chat",
    actionTarget: "tasks",
  },
  {
    id: "artifact-preview",
    name: "Artifact Preview",
    version: "1.0.0",
    category: "Internal",
    permission: "restricted",
    description: "Built-in output preview capabilities that belong to the core shell.",
    source: "Built-in",
    contributions: ["preview cards", "artifact surfaces", "pop-out views"],
    accent: "#c4b5fd",
    headline: "Keep generated outputs visible and ready to revisit.",
    actionLabel: "Open Outputs",
    actionTarget: "settings",
  },
  {
    id: "skills-market",
    name: "Skills Market",
    version: "1.0.0",
    category: "Internal",
    permission: "restricted",
    description: "Internal skill capability surfaces now treated as part of the base product.",
    source: "Built-in",
    contributions: ["skill packs", "catalog metadata", "role recommendations"],
    accent: "#86efac",
    headline: "Rebalance agent capabilities with prebuilt skill patterns.",
    actionLabel: "Open Skills",
    actionTarget: "settings",
    controlCenterSectionId: "skills",
  },
  {
    id: "bridge-channel",
    name: "Bridge Channel",
    version: "1.0.0",
    category: "Internal",
    permission: "full-access",
    description: "Core channel routing and bridge workflows included in the product.",
    source: "Built-in",
    contributions: ["channel adapters", "routing hooks", "event bridges"],
    accent: "#fda4af",
    headline: "Expose message routes and bridge visibility in one place.",
    actionLabel: "Open Channels",
    actionTarget: "settings",
    controlCenterSectionId: "channels",
  },
  {
    id: "ops-telemetry",
    name: "Ops Telemetry",
    version: "1.0.0",
    category: "Internal",
    permission: "restricted",
    description: "Core health and execution telemetry already bundled in the product.",
    source: "Built-in",
    contributions: ["status metrics", "heartbeat cards", "ops summary"],
    accent: "#fbbf24",
    headline: "Track shell health, coverage, and execution signals more visibly.",
    actionLabel: "Open Dashboard",
    actionTarget: "dashboard",
  },
  {
    id: "provider-lab",
    name: "Provider Lab",
    version: "1.0.0",
    category: "Internal",
    permission: "full-access",
    description: "Built-in provider experiments now treated as part of the main product settings.",
    source: "Built-in",
    contributions: ["provider templates", "routing tests", "lab settings"],
    accent: "#60a5fa",
    headline: "Experiment with provider combinations without losing the main setup flow.",
    actionLabel: "Open Settings",
    actionTarget: "settings",
    controlCenterSectionId: "settings",
  },
];

export const DEFAULT_ENABLED_PLUGIN_IDS = INTERNAL_PLUGIN_CATALOG.map(plugin => plugin.id);

export const PLUGIN_CATALOG: PluginSpec[] = [
  {
    id: "figma",
    name: "Figma",
    version: "0.9.0",
    category: "Design",
    permission: "restricted",
    description: "Sync design files, inspect components, and hand off visual specs into the workspace.",
    source: "Official",
    contributions: ["design sync", "component inspect", "handoff links"],
    accent: "#a78bfa",
    headline: "Connect design files and component context directly into your workbench.",
    actionLabel: "Open Figma Setup",
    actionTarget: "settings",
  },
  {
    id: "canva",
    name: "Canva",
    version: "0.8.2",
    category: "Design",
    permission: "restricted",
    description: "Pull marketing assets, edit templates, and route social content drafts through Canva.",
    source: "Official",
    contributions: ["asset export", "template actions", "social drafts"],
    accent: "#38bdf8",
    headline: "Bridge campaign assets and lightweight creative production from Canva.",
    actionLabel: "Open Canva Setup",
    actionTarget: "settings",
  },
  {
    id: "linear",
    name: "Linear",
    version: "1.0.0",
    category: "Project",
    permission: "full-access",
    description: "Create issues, sync delivery status, and turn execution outcomes into Linear follow-up.",
    source: "Official",
    contributions: ["issue sync", "project updates", "delivery handoff"],
    accent: "#818cf8",
    headline: "Push tasks, bugs, and shipping signals into Linear without leaving the desktop shell.",
    actionLabel: "Open Linear Setup",
    actionTarget: "settings",
  },
  {
    id: "notion",
    name: "Notion",
    version: "0.9.4",
    category: "Knowledge",
    permission: "restricted",
    description: "Read project docs, write meeting notes, and connect workspace knowledge to execution flows.",
    source: "Official",
    contributions: ["doc sync", "knowledge pages", "meeting notes"],
    accent: "#94a3b8",
    headline: "Bring structured docs, notes, and lightweight knowledge workflows into the platform.",
    actionLabel: "Open Notion Setup",
    actionTarget: "settings",
  },
  {
    id: "slack",
    name: "Slack",
    version: "0.7.6",
    category: "Communication",
    permission: "full-access",
    description: "Route alerts, approvals, and team handoff messages between the platform and Slack channels.",
    source: "Official",
    contributions: ["channel alerts", "approval routing", "team handoff"],
    accent: "#f472b6",
    headline: "Keep human teams in the loop with Slack-based approvals and notifications.",
    actionLabel: "Open Slack Setup",
    actionTarget: "settings",
  },
  {
    id: "github",
    name: "GitHub",
    version: "0.8.7",
    category: "Development",
    permission: "full-access",
    description: "Link repositories, surface pull request context, and sync engineering work back to the platform.",
    source: "Official",
    contributions: ["repo links", "pull request sync", "engineering context"],
    accent: "#60a5fa",
    headline: "Connect repo activity and code delivery context to agent execution.",
    actionLabel: "Open GitHub Setup",
    actionTarget: "settings",
  },
  {
    id: "jira",
    name: "Jira",
    version: "0.8.9",
    category: "Project",
    permission: "full-access",
    description: "Track delivery tickets, sprint status, and escalation paths for operations-heavy teams.",
    source: "Official",
    contributions: ["issue sync", "sprint planning", "approval routing"],
    accent: "#0ea5e9",
    headline: "Bring sprint tracking and issue triage into the execution loop.",
    actionLabel: "Open Jira Setup",
    actionTarget: "settings",
  },
  {
    id: "trello",
    name: "Trello",
    version: "0.7.4",
    category: "Project",
    permission: "restricted",
    description: "Sync lightweight boards, campaign stages, and checklist-based operating routines.",
    source: "Official",
    contributions: ["board sync", "project updates", "template actions"],
    accent: "#38bdf8",
    headline: "Turn lightweight kanban boards into visible operating context.",
    actionLabel: "Open Trello Setup",
    actionTarget: "settings",
  },
  {
    id: "hubspot",
    name: "HubSpot",
    version: "0.9.1",
    category: "Sales",
    permission: "full-access",
    description: "Read contacts, push deal notes, and sync customer follow-up steps with the platform.",
    source: "Official",
    contributions: ["crm sync", "deal updates", "team handoff"],
    accent: "#fb923c",
    headline: "Link marketing, sales, and customer follow-up into one desktop flow.",
    actionLabel: "Open HubSpot Setup",
    actionTarget: "settings",
  },
  {
    id: "salesforce",
    name: "Salesforce",
    version: "0.8.5",
    category: "Sales",
    permission: "full-access",
    description: "Sync enterprise leads, opportunity status, and service handoff checkpoints.",
    source: "Official",
    contributions: ["crm sync", "issue sync", "delivery handoff"],
    accent: "#60a5fa",
    headline: "Expose enterprise pipeline state and follow-up actions without leaving the shell.",
    actionLabel: "Open Salesforce Setup",
    actionTarget: "settings",
  },
  {
    id: "shopify",
    name: "Shopify",
    version: "0.8.3",
    category: "Commerce",
    permission: "full-access",
    description: "Pull store orders, update product copy, and sync storefront operations with content work.",
    source: "Official",
    contributions: ["commerce sync", "asset export", "project updates"],
    accent: "#22c55e",
    headline: "Connect catalog operations, order signals, and marketing assets in one place.",
    actionLabel: "Open Shopify Setup",
    actionTarget: "settings",
  },
  {
    id: "google-drive",
    name: "Google Drive",
    version: "0.9.0",
    category: "Storage",
    permission: "restricted",
    description: "Browse shared assets, fetch docs, and attach project references directly into runs.",
    source: "Official",
    contributions: ["doc sync", "asset export", "handoff links"],
    accent: "#fbbf24",
    headline: "Pull shared files and working documents into your execution context.",
    actionLabel: "Open Drive Setup",
    actionTarget: "settings",
  },
  {
    id: "airtable",
    name: "Airtable",
    version: "0.8.8",
    category: "Automation",
    permission: "restricted",
    description: "Sync campaign bases, lightweight operations records, and structured queues into the platform.",
    source: "Official",
    contributions: ["base sync", "project updates", "knowledge pages"],
    accent: "#f59e0b",
    headline: "Use operational tables as live signal boards for the team.",
    actionLabel: "Open Airtable Setup",
    actionTarget: "settings",
  },
  {
    id: "discord",
    name: "Discord",
    version: "0.7.2",
    category: "Communication",
    permission: "full-access",
    description: "Send alerts, mod queue updates, and community handoff messages into Discord channels.",
    source: "Official",
    contributions: ["channel alerts", "approval routing", "community sync"],
    accent: "#818cf8",
    headline: "Keep community operations visible when the team is not living in Slack.",
    actionLabel: "Open Discord Setup",
    actionTarget: "settings",
  },
  {
    id: "x",
    name: "X",
    version: "0.8.6",
    category: "Social",
    permission: "full-access",
    description: "Prepare tweet drafts, sync posting queues, and connect lightweight publishing workflows.",
    source: "Official",
    contributions: ["social drafts", "publish queue", "channel alerts"],
    accent: "#111827",
    headline: "Route short-form content production and posting rhythm through the shell.",
    actionLabel: "Open X Setup",
    actionTarget: "settings",
  },
  {
    id: "youtube",
    name: "YouTube",
    version: "0.7.9",
    category: "Social",
    permission: "restricted",
    description: "Coordinate upload metadata, content scheduling, and channel-side publishing prep.",
    source: "Official",
    contributions: ["publish queue", "knowledge pages", "delivery handoff"],
    accent: "#ef4444",
    headline: "Support channel publishing prep, metadata management, and release follow-up.",
    actionLabel: "Open YouTube Setup",
    actionTarget: "settings",
  },
  {
    id: "zapier",
    name: "Zapier",
    version: "0.8.4",
    category: "Automation",
    permission: "restricted",
    description: "Bridge no-code automations, webhooks, and lightweight trigger chains into operating flows.",
    source: "Official",
    contributions: ["workflow bridge", "routing hooks", "event bridges"],
    accent: "#f97316",
    headline: "Turn outside automations into clean triggers the team can supervise.",
    actionLabel: "Open Zapier Setup",
    actionTarget: "settings",
  },
  {
    id: "dropbox",
    name: "Dropbox",
    version: "0.7.7",
    category: "Storage",
    permission: "restricted",
    description: "Sync asset folders, review links, and shared customer files into the workspace.",
    source: "Official",
    contributions: ["asset export", "handoff links", "doc sync"],
    accent: "#2563eb",
    headline: "Keep media assets and customer file exchanges connected to the workbench.",
    actionLabel: "Open Dropbox Setup",
    actionTarget: "settings",
  },
];

export const PLUGIN_PACKS: PluginPackSpec[] = [
  {
    id: "creative-growth-pack",
    iconLabel: "palette",
    title: "Creative Growth Pack",
    description: "Figma, Canva, X, YouTube, and cloud assets for design handoff, content growth, and campaign production.",
    pluginIds: ["figma", "canva", "x", "youtube", "google-drive", "dropbox"],
    accent: "#a855f7",
  },
  {
    id: "operations-revenue-pack",
    iconLabel: "people",
    title: "Operations Revenue Pack",
    description: "Project tracking, customer follow-up, storefront coordination, and team communication in one operating layer.",
    pluginIds: ["linear", "notion", "slack", "hubspot", "salesforce", "shopify", "discord"],
    accent: "#fb923c",
  },
  {
    iconLabel: "bolt",
    id: "delivery-automation-pack",
    title: "Delivery Automation Pack",
    description: "Engineering delivery, issue routing, and no-code automation for shipping and orchestration teams.",
    pluginIds: ["github", "jira", "trello", "zapier", "airtable"],
    accent: "#3b82f6",
  },
];

export function getPluginById(pluginId: string) {
  return PLUGIN_CATALOG.find(plugin => plugin.id === pluginId)
    ?? INTERNAL_PLUGIN_CATALOG.find(plugin => plugin.id === pluginId)
    ?? null;
}
