export interface PresetTask {
  id: string;
  name: string;
  description: string;
  icon: string;
  instruction: string;
  category: 'family' | 'finance' | 'health' | 'hobby' | 'education' | 'emotion';
}

export const PRESET_TASKS: PresetTask[] = [
  // 家庭与生活
  {
    id: 'new-mom',
    name: '宝妈',
    description: '围绕育儿、亲子日常创作短剧脚本',
    icon: '👶',
    instruction: '以宝妈视角创作一段短剧脚本，主题是带娃日常中的搞笑或感人瞬间，时长约300字，风格温馨有共鸣。',
    category: 'family',
  },
  {
    id: 'housewife',
    name: '家庭主妇',
    description: '家务、生活智慧与家庭关系题材',
    icon: '🏠',
    instruction: '以家庭主妇视角创作一段短剧脚本，展现她在家庭琐事中的智慧与幽默，约300字，风格贴近生活。',
    category: 'family',
  },
  {
    id: 'stay-home-dad',
    name: '全职爸爸',
    description: '爸爸带娃的反差萌与成长故事',
    icon: '👨‍👧',
    instruction: '以全职爸爸视角创作一段短剧脚本，展现他带娃时的手忙脚乱与温情时刻，约300字，风格轻松搞笑。',
    category: 'family',
  },
  {
    id: 'newlyweds',
    name: '新婚夫妻',
    description: '婚后磨合、甜蜜日常与成长',
    icon: '💑',
    instruction: '以新婚夫妻视角创作一段短剧脚本，展现婚后磨合期的甜蜜与小摩擦，约300字，风格甜虐兼具。',
    category: 'family',
  },
  {
    id: 'single-mom',
    name: '单亲妈妈',
    description: '独立坚强、与孩子共同成长',
    icon: '💪',
    instruction: '以单亲妈妈视角创作一段短剧脚本，展现她独自撑起家庭的坚韧与温柔，约300字，风格励志感人。',
    category: 'family',
  },
  {
    id: 'mother-in-law',
    name: '婆媳关系',
    description: '婆媳矛盾与和解的情感博弈',
    icon: '👩‍👩‍👦',
    instruction: '创作一段婆媳关系短剧脚本，展现婆媳之间的误解、矛盾与最终和解，约300字，风格真实有张力。',
    category: 'family',
  },
  // 财经与职场
  {
    id: 'finance-expert',
    name: '理财专家',
    description: '理财知识普及与财富增值故事',
    icon: '💰',
    instruction: '以理财专家视角创作一段短剧脚本，通过一个普通人理财翻身的故事传递财富管理理念，约300字，风格励志实用。',
    category: 'finance',
  },
  {
    id: 'side-hustle',
    name: '副业达人',
    description: '下班后开启副业的奋斗历程',
    icon: '🚀',
    instruction: '以副业达人视角创作一段短剧脚本，展现普通上班族利用业余时间开拓副业的心路历程，约300字，风格励志接地气。',
    category: 'finance',
  },
  {
    id: 'career-elite',
    name: '职场精英',
    description: '职场竞争、晋升与职业成长',
    icon: '💼',
    instruction: '以职场精英视角创作一段短剧脚本，展现职场中的竞争、合作与个人成长，约300字，风格爽感十足。',
    category: 'finance',
  },
  {
    id: 'entrepreneur',
    name: '创业者',
    description: '创业路上的挫折、坚持与突破',
    icon: '🏆',
    instruction: '以创业者视角创作一段短剧脚本，展现创业初期遭遇困境却坚持突破的故事，约300字，风格燃情励志。',
    category: 'finance',
  },
  {
    id: 'ecommerce-seller',
    name: '电商卖家',
    description: '电商运营、爆款打造与客户故事',
    icon: '🛒',
    instruction: '以电商卖家视角创作一段短剧脚本，展现从选品到爆款的奋斗过程，约300字，风格真实有代入感。',
    category: 'finance',
  },
  // 健康与美容
  {
    id: 'fitness-blogger',
    name: '健身博主',
    description: '健身打卡、身材管理与自律故事',
    icon: '💪',
    instruction: '以健身博主视角创作一段短剧脚本，展现坚持健身改变体型与生活状态的历程，约300字，风格励志有感染力。',
    category: 'health',
  },
  {
    id: 'makeup-blogger',
    name: '美妆博主',
    description: '美妆技巧、变美心路与自信故事',
    icon: '💄',
    instruction: '以美妆博主视角创作一段短剧脚本，展现通过美妆找回自信的故事，约300字，风格甜美有共鸣。',
    category: 'health',
  },
  {
    id: 'skincare-expert',
    name: '护肤专家',
    description: '护肤知识科普与肌肤改善历程',
    icon: '✨',
    instruction: '以护肤专家视角创作一段短剧脚本，通过一个肌肤问题困扰者的改善历程传递护肤理念，约300字，风格专业温暖。',
    category: 'health',
  },
  {
    id: 'weight-loss',
    name: '减肥博主',
    description: '减肥历程、反弹与最终成功',
    icon: '🥗',
    instruction: '以减肥博主视角创作一段短剧脚本，展现减肥路上的挣扎、反弹与最终成功，约300字，风格真实励志。',
    category: 'health',
  },
  // 兴趣与创作
  {
    id: 'food-blogger',
    name: '美食博主',
    description: '美食探店、家常菜与饮食文化',
    icon: '🍜',
    instruction: '以美食博主视角创作一段短剧脚本，围绕一道家常菜背后的情感故事展开，约300字，风格温馨有烟火气。',
    category: 'hobby',
  },
  {
    id: 'travel-blogger',
    name: '旅行博主',
    description: '旅途奇遇、文化碰撞与成长',
    icon: '✈️',
    instruction: '以旅行博主视角创作一段短剧脚本，展现一次旅途中意外相遇带来的人生感悟，约300字，风格治愈有深度。',
    category: 'hobby',
  },
  {
    id: 'gaming-blogger',
    name: '游戏博主',
    description: '游戏竞技、团队协作与热血故事',
    icon: '🎮',
    instruction: '以游戏博主视角创作一段短剧脚本，展现电竞团队在关键赛事中逆风翻盘的热血时刻，约300字，风格燃情爽感。',
    category: 'hobby',
  },
  {
    id: 'book-blogger',
    name: '读书博主',
    description: '阅读改变命运与知识启迪故事',
    icon: '📚',
    instruction: '以读书博主视角创作一段短剧脚本，展现一本书如何在关键时刻改变一个人的选择，约300字，风格深刻有启发。',
    category: 'hobby',
  },
  // 教育与成长
  {
    id: 'parenting-expert',
    name: '育儿专家',
    description: '科学育儿、亲子沟通与成长陪伴',
    icon: '🌱',
    instruction: '以育儿专家视角创作一段短剧脚本，展现一个亲子沟通难题的化解过程，约300字，风格温暖有教育意义。',
    category: 'education',
  },
  {
    id: 'english-teacher',
    name: '英语老师',
    description: '语言学习、文化交流与突破自我',
    icon: '🌍',
    instruction: '以英语老师视角创作一段短剧脚本，展现一个学生克服语言障碍走向自信的故事，约300字，风格励志温馨。',
    category: 'education',
  },
  {
    id: 'psychologist',
    name: '心理咨询师',
    description: '心理疗愈、情绪管理与内心成长',
    icon: '🧠',
    instruction: '以心理咨询师视角创作一段短剧脚本，展现一次咨询如何帮助来访者走出困境，约300字，风格细腻有共鸣。',
    category: 'education',
  },
  {
    id: 'positive-blogger',
    name: '正能量博主',
    description: '逆境翻盘、自我激励与人生感悟',
    icon: '☀️',
    instruction: '以正能量博主视角创作一段短剧脚本，展现一个普通人在低谷期重新找到方向的故事，约300字，风格励志感人。',
    category: 'education',
  },
  // 情感与关系
  {
    id: 'relationship-blogger',
    name: '情感博主',
    description: '爱情、分手与重新出发的故事',
    icon: '💝',
    instruction: '以情感博主视角创作一段短剧脚本，展现一段感情从误解到和解的情感历程，约300字，风格甜虐有张力。',
    category: 'emotion',
  },
  {
    id: 'sarcastic-wife',
    name: '毒舌媳妇',
    description: '犀利吐槽背后的真实情感',
    icon: '😏',
    instruction: '以毒舌媳妇视角创作一段短剧脚本，展现她用犀利方式表达爱意的反差萌故事，约300字，风格搞笑有反转。',
    category: 'emotion',
  },
  {
    id: 'single-noble',
    name: '单身贵族',
    description: '享受单身生活与意外遇见爱情',
    icon: '👑',
    instruction: '以单身贵族视角创作一段短剧脚本，展现一个享受独处的人意外坠入爱河的故事，约300字，风格甜蜜有惊喜。',
    category: 'emotion',
  },
  {
    id: 'divorce-blogger',
    name: '离婚博主',
    description: '婚姻破裂后的重建与新生',
    icon: '🦋',
    instruction: '以离婚博主视角创作一段短剧脚本，展现离婚后重新找回自我、开启新生活的故事，约300字，风格励志治愈。',
    category: 'emotion',
  },
];

export const CATEGORY_LABELS: Record<PresetTask['category'], string> = {
  family: '家庭与生活',
  finance: '财经与职场',
  health: '健康与美容',
  hobby: '兴趣与创作',
  education: '教育与成长',
  emotion: '情感与关系',
};
